### ISSUE TITLE
A few suggestions for this theme

### ISSUE THREAD

**Issue by yagomont** [Luwx/Fluent-kvantum#1]
Hi, I want to let you know this is a great kvantum theme.
However, as an user of such theme, I feel obligated to send some useful feedback about it. Let's begin.

1. (bad) Set vlc as an opaque application: transparency messes up video playback
2. (suggestion) Set all highlight colors to #3671bd (color-picked from a MacOS screenshot, better contrast than current light blue)
3. (mild) Make menus more transparent, too dark compared to rest of the theme right now (30% extra is good) 
4. (bad) Some window elements look bad without transparency (Is this an issue with the theme? I'm not sure what's happening.)
![see here for 4.](https://user-images.githubusercontent.com/14876659/49670151-6d19e800-fa42-11e8-8f88-2d961e8bf6fd.png)

Those are some things I noticed and thought about while using this theme. I used... unorthodox ways to edit the theme and ended with 1., 2. and 3. resolved. Unfortunately, I have no idea if 4. is intentional or even why it's like that.

**Comment by Luwx** [comment]
Thanks for the feedback! 

I'm not quite finished with this yet, there are some leftovers from the other theme (I didn't change the colors), so I'll experiment a bit. 

> (bad) Set vlc as an opaque application: transparency messes up video playback

Man, I don't know why I took it out of the blacklist.. 


> (mild) Make menus more transparent, too dark compared to rest of the theme right now (30% extra is good)

Yeah

> (bad) Some window elements look bad without transparency (Is this an issue with the theme? I'm not sure what's happening.)

There are some elements that kvantum cannot make transparent, like QML parts. But I also intended to not use transparency on everything, similar to Windows designs, so I left some parts opaque. As you can see, things are looking very out of place, I think it's better to add some transparency to them :)

I'll also try to figure out why konsole menubar text is not centered..

**Comment by Luwx** [comment]
Fixed in https://github.com/Luwx/Fluent-kvantum/commit/e4e2e917faddee69b297667013fe424976ae454b .

**Comment by Genxster1998** [comment]
I like the current way ,toolbar is dark in comparison to others panel give unique look ,otherwise it will be similar to other simple translucent theme already available there .
