### ISSUE TITLE
[Wayland]Sidebar view in KDE System settings is not visible at all with this theme

### ISSUE THREAD

**Issue by mthw0** [Luwx/Fluent-kvantum#3]
Could you look at it?
See: https://imgur.com/a/CGndhrG
Or could you tell me a workaround?

**Comment by yagomont** [comment]
Looks like a driver glitch, or a bug in recent KDE software.
I don't have a computer right now so I can't confirm this bug, but during my time using this theme, I can assure this didn't happen.

**Comment by Luwx** [comment]
What color scheme are you using?

**Comment by mthw0** [comment]
@Luwx I tried with Breeze Dark, Breath Dark, Kvantum, Breeze light and others, no difference. Also you should know that in the screenshot there is actually transparent area with blur, not a black area (it just isn't captured by the screenshot). And finally, this is on Plasma Wayland.

EDIT: Before you ask, it works fine on Plasma Xorg.

**Comment by Luwx** [comment]
This seems to be a upstream bug in KDE or Kvantum indeed. Can you reproduce this with other full transparent themes aswell?

**Comment by mthw0** [comment]
It looks like other themes are affected too. Tested also with Aether-kv and MateriaBlur. I will report this to Kvantum then.

EDIT: Done: https://github.com/tsujan/Kvantum/issues/343
