### ISSUE TITLE
Progressbar isnt smooth 

### ISSUE THREAD

**Issue by Genxster1998** [Luwx/Fluent-kvantum#4]
You can see anywhere in system that qt widgets progessbar is not smooth at ends ,its glitched like inconsistent draw ...

_Sent from my Redmi Note 3 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by Luwx** [comment]
Can you send a screenshot?

**Comment by Genxster1998** [comment]
I am at my college hostel without my laptop :worried:
You can check that in sm player or dolphin video/audio file preview
