### ISSUE TITLE
[Light]KDE System Settings: backgrounds are black instead of (most likely) transparent

### ISSUE THREAD

**Issue by mthw0** [Luwx/Fluent-kvantum#5]
See: https://imgur.com/a/AxENIEF also the menu shown is not readable. The same menu is also in Elisa and is not readable too.

PS.: I know Light theme is WIP but I still wanted to let you know about this, in case you didn't notice.

**Comment by Luwx** [comment]
I haven't had time latelly to finish the light version, it's about 40% done..

If i recall correctly, these qml widgets in system settings and other apps get the color from color schemes or from the theme [general colors] in .kvconfig, so it probably needs some tweaking there.

**Comment by Luwx** [comment]
Fixed.
