### ISSUE TITLE
Light decoration

### ISSUE THREAD

**Issue by jbouter** [Luwx/Fluent-kvantum#6]
I can't, for the life of me, figure out what window decorations are used in the screenshot for the light theme. The edges seem curved, and the transparency disabled. This is exactly what I am looking for.

Could you please document what settings you are using with your screenshots? I'm also interested to see what plasma theme is being used. 

Thanks in advance.

**Comment by Luwx** [comment]
For the decoration, you can use https://github.com/yagomont/material-decoration-bt and https://github.com/alex47/KDE-Rounded-Corners to round the corners.

The plasma theme is Aex light, if I recall correctly.
