### ISSUE TITLE
[Dark] Elisa has completely black backgrounds instead of transparent.

### ISSUE THREAD

**Issue by StarrKiss** [Luwx/Fluent-kvantum#7]
![When](https://user-images.githubusercontent.com/13007697/60289447-08d64d00-98dc-11e9-8acd-c055704c186a.png)

**Comment by Luwx** [comment]
Unfortunately, Kvantum doesn't support transparency/blurring in QML apps, like Elisa. See more about it [here](https://github.com/tsujan/Kvantum/issues/387).
