### ISSUE TITLE
The background / design of container seems too light.

### ISSUE THREAD

**Issue by ghost** [Luwx/Fluent-kvantum#9]
The mentioned bug is on the left bottom side of the provided image.
This affects programs like Qt Designer where the working space has light background.

![Image](https://imgur.com/VpA3UVs.png)

![Qt Designer example](https://imgur.com/LQdP3RK.png)

I made some hotfixes which might not be appropriate but does the job for me.
[Fluent-Dark-Me.zip](https://github.com/Luwx/Fluent-kvantum/files/3342221/Fluent-Dark-Me.zip)

![Example of my changes](https://imgur.com/7465JjI.png)

**Comment by Luwx** [comment]
Thanks for the feedback! I'll look into it.

**Comment by ghost** [comment]
Thank you for fixes.
